### ISSUE TITLE
Feature Request: Add support for screen capture

### ISSUE THREAD

**Issue by rkr1209** [eLearning-BS23/moodle-quizaccess_proctoring#11]
Feature Request:

- Add support to also save screenshots of the students screen

**Comment by michaelhaddad4** [comment]
I second this request. I would like to be able to see a screenshot of the screen(s) at the time the pic is taken.

**Comment by doctsh** [comment]
is there any update on this request? can we have screenshot in addition with webcam feed?

**Comment by AnowarCST** [comment]
@doctsh Not yet, we will try to cover that in the upcoming releases.

**Comment by nadavkav** [comment]
In our Moodle, we use https://html2canvas.hertzen.com/ to capture a screen shoot, for a ticket support system we developed.
It is a very simple and useful JS library.
Please consider using it.

**Comment by doctsh** [comment]
@nadavkav yes true. html2canvas is very handy i tested it is working with this plugin...but need to be properly done to handle permission issues. Hope this can be done by @AhnafMuttaki

**Comment by AhnafMuttaki** [comment]
This feature is introduced in new version. Please check.
