### ISSUE TITLE
Support for mobile devices

### ISSUE THREAD

**Issue by theamanjs** [eLearning-BS23/moodle-quizaccess_proctoring#14]
I've tested this plugin locally on my desktop and mobile. I've tried both old and this new repo code. I want to share the steps while I tried using this on mobile locally and it didn't work.

## Prerequisites
Install the plugin in moodle

## Steps to reproduce (What I did)
1. Create a quiz enabling `Webcam identity validation` to `must be acknowledged before starting an attempt`
2. Go to 'localhost' and take a quiz
3. Access the localhost from mobile. For that change the `$CFG->wwwroot   = '<your_local_ip>';` in `config.php` of moodle 
4. Access the quiz from mobile by IP address of pc and it is not able to access the webcam. Attaching screenshot below

![3fd77bad-4d72-46e9-b12f-79487e9170e7](https://user-images.githubusercontent.com/38748298/100732138-57054f00-33f2-11eb-9e4a-dff314921224.jpeg)

## Mobile Device Info
Browser: Chrome
OS: Android

**Comment by theamanjs** [comment]
This is working fine. I've used [chrome debugging + port forwarding](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/local-server) to test on localhost and it has given me superb result. Thank you for creating this plugin.

**Comment by AnowarCST** [comment]
Sounds good. Thanks.
