### ISSUE TITLE
Hardcoded

### ISSUE THREAD

**Issue by dinism** [eLearning-BS23/moodle-quizaccess_proctoring#25]
I'm a PT-PT translator.
![imagem](https://user-images.githubusercontent.com/14828021/106774970-94789980-663a-11eb-8b2b-a0d0b29542bd.png)

![imagem](https://user-images.githubusercontent.com/14828021/106775482-11a40e80-663b-11eb-887f-6dc0b3a2e7ef.png)

**Comment by AhnafMuttaki** [comment]
Issue fixed and created PR.

**Comment by AhnafMuttaki** [comment]
Camera warning message fixed.

**Comment by AhnafMuttaki** [comment]
Hardcoded messages are fixed
