### ISSUE TITLE
error on viewing proctoring report

### ISSUE THREAD

**Issue by hafriz** [eLearning-BS23/moodle-quizaccess_proctoring#38]
step i produce the error : 

after installing this accessrule proctoring, create quiz and attempt the quiz as student. 

after finish atempt, login as admin and view the procotoring report. the error as below 

thanks 

Debug info: Unknown column 'e.awsscore' in 'field list'
SELECT e.id as reportid, e.userid as studentid, e.webcampicture as webcampicture, e.status as status,
e.timemodified as timemodified, u.firstname as firstname, u.lastname as lastname, u.email as email, e.awsscore, e.awsflag
from mdl_quizaccess_proctoring_logs e INNER JOIN mdl_user u ON u.id = e.userid
WHERE e.courseid = '10409' AND e.quizid = '277460' AND u.id = '36264'
[array (
)]
Error code: dmlreadexception

**Comment by hafriz** [comment]
after uninstall then reinstall the new version, it is working correctly and no more error. it seems upgrade missing the column in mdl_quizaccess_proctoring_logs

**Comment by AhnafMuttaki** [comment]
can you please mention from which version you are upgrading because upgrade.php contains the aws related columns and i did not face this issue.

**Comment by hafriz** [comment]
@AhnafMuttaki a version before this face analyze implementation. i have full uninstall the old version and reinstall back. now it's working

**Comment by AhnafMuttaki** [comment]
Closing the issue as upgrade.php consists the field addition and i could not produce the issue while i tried to upgrade.
