### ISSUE TITLE
cron run for background image analysis

### ISSUE THREAD

**Issue by hafriz** [eLearning-BS23/moodle-quizaccess_proctoring#39]
hi,

is the module has cron run for face image analysis? for BS face analysis, who/where i can contact to test the features? 

thanks

**Comment by AhnafMuttaki** [comment]
Please use the below BS host and token in settings page.
**BS API host:** http://52.76.20.96:8001
**BS API Token:** 5f0a3b62-7c74-4645-8ce3-c758e9b5c992

- Please edit profile and set e profile image first for matching with images.
- Please note that this token is for demo purposes [It may expire soon]. 
- Please contact with brainstation23 or you can leave a comment here if you want to purchase this service.

**Comment by hafriz** [comment]
hi AhnafMuttaki, 

i have try BS method to face analysis, i have try to use analyze function in protoring modules, and also use postman to see return data. it seems when i use the image captured from proctoring. it failed to analyze the image. i have try to send image1 and image2 using the same image still facematched return false. 

if i'm using other image captured using handphone / ordinary camera it's working
