### ISSUE TITLE
image facematched return false when comparing using image captured by proctoring

### ISSUE THREAD

**Issue by hafriz** [eLearning-BS23/moodle-quizaccess_proctoring#41]
hi @AhnafMuttaki 

i have try BS method to face analysis, i have try to use analyze function in protoring modules, and also use postman to see return data. it seems when i use the image captured from proctoring. it failed to analyze the image. i have try to send image1 and image2 using the same image still facematched return false. 

if i'm using other image captured using handphone / ordinary camera it's working @

_Originally posted by @hafriz in https://github.com/eLearning-BS23/moodle-quizaccess_proctoring/issues/39#issuecomment-909891458_

**Comment by hafriz** [comment]
after further test, it seems there is a problem when using curl PHP to post the image to the face match server. i have tried on multiple servers and it's giving a problem. 

what's work for me is i change the method from using curl to using pear http_request2 method and i'm also using my own image library to compare with webcam snapshot not using the image from user profile upload. i also change the image size for the webcam snapshot to a bigger size.

**Comment by AhnafMuttaki** [comment]
Did you set your profile picture first ? you need to set your profile picture to be able to compare your screenshot. We did not find any issue with BS face match. please see the below screenshot where facematch was successful.

![image](https://user-images.githubusercontent.com/19352999/133036401-c29c1b8b-fd92-4f41-967a-64b5d874f7ba.png)

Please check if following things are set up correctly before trying facematch.

1. Your profile picture is set
2. Facematch is enabled in proctoring settings. See the below screenshot.
![image](https://user-images.githubusercontent.com/19352999/133036651-d21faa19-7e7e-4018-b204-bcdfcf5ca26e.png)

3. BS URL and token is setup correctly in settings
![image](https://user-images.githubusercontent.com/19352999/133036784-0739f243-2c4d-4c01-9dd5-3afc456c2b11.png)


As we did not find any issue we are closing this issue.
