### ISSUE TITLE
no share screen button when Face ID validate on quiz start is on

### ISSUE THREAD

**Issue by hafriz** [eLearning-BS23/moodle-quizaccess_proctoring#43]
1. there is no share screen button when face ID validate is on. 

2. when the face is validated successfully, and the user starts the quiz, it open the quiz page but then close back and the user is redirected back to validate page although already validated

thanks

**Comment by AhnafMuttaki** [comment]
- We have released a new version which fixed some of the issues. Please check this one.
- Please beinformed that to be able to use face validation and screenshare you need to have https and also you need to allow screenshare and webcam access from browser security. In our test of the new version we found everything is working fine.
