### ISSUE TITLE
JS alert showing when working with SEB

### ISSUE THREAD

**Issue by azmatksa** [eLearning-BS23/moodle-quizaccess_proctoring#48]
Hi, 

I'm running proctoring plugin with safe exams browser (SEB) it shows me JS alert that "You need to keep parent window open" and when we click ok the quiz window become closed! 

![image](https://user-images.githubusercontent.com/49816686/148420165-233a7ea3-b1b5-41ea-a928-8456e9e9d9c5.png)

**Comment by azmatksa** [comment]
I noticed error disappeared when I set browser security to NONE in moodle quiz settings. 

![image](https://user-images.githubusercontent.com/49816686/148679211-8790e616-2ffd-4c8b-b2f6-f7dbf02c808e.png)

**Comment by shadman-ahmed-bs23** [comment]
A new moodle 4 compatible version is released. The new version shouldn't have this issue. Please check it out.

**Comment by blanderson22** [comment]
@azmatksa How were you able to allow Safe Exam Browser and the Moodle Proctoring plugin to work simultaneously? We are currently needing that solution, but when I open our Moodle quiz in SEB with the proctoring plugin enabled, we are not able to get past the webcam acknowledgement. In our testing, checking the webcam acknowledgement checkbox does not enable the "Start Quiz" button. I look forward to your reply!
