### ISSUE TITLE
JS Alert moving to next quiz activity

### ISSUE THREAD

**Issue by scloudsa** [eLearning-BS23/moodle-quizaccess_proctoring#53]
We have set up proctoring(Not using SEB). Tested with browser security enabled and disabled and still get the same JS Alert "You need to keep parent window open" popping up when completing the first quiz with no issue and the alert popping up when accessing the next quiz which closes the tab and reverts to the previous tab with the proctoring acknowledgement.

Please assist on how to resolve this issue. We are using Moodle 3.11.5 with the latest version of the plugin.

**Comment by shadman-ahmed-bs23** [comment]
A new moodle 4 compatible version is released. The new version shouldn't have this issue. Please check it out.
