### ISSUE TITLE
Using AWS Rekognition for Facematch

### ISSUE THREAD

**Issue by swliang** [eLearning-BS23/moodle-quizaccess_proctoring#58]
If I am using Amazon Rekognition for the Facematch, what is the IAM role permission required to be created? 

I have given full access to rekognition and also tried giving full administrator access but when I check on AWS Rekognition side, there is no collection id created, there is no data passed to AWS rekognition for verification. 

Is there other configuration need to be done?

Moodle Version: 3.11.5+ (Build: 20220308) 
Plugin Version: [1.2.42]

**Comment by AhnafMuttaki** [comment]
As this is not an issue. I am closing this. Please communicate in the following email if you need any support. (tahmina@brainstation-23.com)
