### ISSUE TITLE
Start Quiz is disabled

### ISSUE THREAD

**Issue by stharasingh** [eLearning-BS23/moodle-quizaccess_proctoring#59]
Hi,
I am glad we have a Proctoring plugin. After the Proctoring plugin version1.2.42 was installed the start quiz is disabled even after accepting the agreement (Moodle version 3.10.10). Is there something we aren't doing right? I even tried enabling screen share, ideally it is not required as a few of the students use iPads. I'll greatly appreciate your response. Sincerely.

**Comment by AhnafMuttaki** [comment]
Unfortunately the issue was occurring due to browser limitation. Screen share feature was dependent on a certain browser info which does not follow W3C standard unfortunately. That is why we had to remove the screenshare feature. In latest version the issue is fixed.
