### ISSUE TITLE
Moodle 4.0 installed in Ubuntu virtual machine - not able to start quiz 

### ISSUE THREAD

**Issue by kumarakshay01** [eLearning-BS23/moodle-quizaccess_proctoring#63]
Hi Team,
I have configured moodle 4.0 in ubuntu 20.4 virtual machine and configured [moodle-quizaccess_proctoring] but I am not able to start the quiz - the plugin doesn't ask to share screen and shows a camera, I am also not able to start the quiz - tried with 3.11, 3.10 and 3.9 versions as well.  Can some one please help :)

**Comment by AhnafMuttaki** [comment]
A new moodle 4 compatible version is released. Please check it out.
