### ISSUE TITLE
Create pdf from captured images

### ISSUE THREAD

**Issue by registerme1963** [eLearning-BS23/moodle-quizaccess_proctoring#67]
Instead of storing multiple images, why not embed images along with timestamp in a separate pdf for each student. Since TCPDF is already available in the MOODLE core, this may be possible. Course tutor may backup the pdf. Option may be given to download all pdfs in a single zip file and also delete. This may save the disk usage

**Comment by shadman-ahmed-bs23** [comment]
Thanks for your suggestion. But we need separate image urls  to run face match algorithms on those. 

Closing this issue. Feel free to reopen for further discussion
