### ISSUE TITLE
Error in upgrade code

### ISSUE THREAD

**Issue by davidherney** [eLearning-BS23/moodle-quizaccess_proctoring#68]
Hi...

You have an error into the **xmldb_quizaccess_proctoring_upgrade** function. When call the **upgrade_plugin_savepoint** function the last parameters are not correct.

Actual use:
`upgrade_plugin_savepoint(true, 2021061104, 'mod', 'quizaccess_proctoring');`

Change to:
`upgrade_plugin_savepoint(true, 2021061104, 'quizaccess', 'proctoring');`

Saludos

**Comment by shadman-ahmed-bs23** [comment]
This issue is resolved with latest release. Closing this issue.
