### ISSUE TITLE
Moodle Proctoring plugin and Safe Exam Browser?

### ISSUE THREAD

**Issue by blanderson22** [eLearning-BS23/moodle-quizaccess_proctoring#73]
I've read several responses that have mentioned their use of Safe Exam Browser with the Moodle Proctoring Plugin. 

Is there a customization of the code required to make them compatible, or a specific configuration needed to make it work? 

We are currently needing that solution, but when I open our Moodle quiz in SEB with the Moodle Proctoring plugin enabled, we are not able to get past the webcam acknowledgement. In our testing, checking the webcam acknowledgement checkbox does not enable the "Start Quiz" button. I look forward to your reply!

**Comment by shadman-ahmed-bs23** [comment]
We will look into the issue you have mentioned and get back to you as early as possible. Thanks.

**Comment by takielias** [comment]
@blanderson22 Please share the OS details.

![FireShot Webpage Screenshot #015 - 'Editing Quiz' - moodle3117 test](https://user-images.githubusercontent.com/38932580/196019518-2c93ce1c-35f0-40a8-8fd1-a672286f1dcc.png)

The above SEB config was tested in windows os. And it was working fine. 
For the above config, you would get a Button named **Launch Safe Exam Browser**. Click it.

![image](https://user-images.githubusercontent.com/38932580/196019592-3ef05eec-401c-404e-9c62-d0fc61ae244e.png)

Now, you might get a popup window. Click **Open Link**

![image](https://user-images.githubusercontent.com/38932580/196019668-b9465e4b-3222-430a-96f0-bc6ce78174e4.png)

You have to login into your LMS using SEB first. Once you are logged in, You will get the **Attempt quiz now** button.

That's it. Please feel free to ask any questions regarding this issue.

**Comment by shadman-ahmed-bs23** [comment]
Hi @blanderson22, closing this issue. Feel free to reopen or open a new one if you have any issue. Thanks.
