### ISSUE TITLE
Problems with face recognition in the browser.

### ISSUE THREAD

**Issue by unesco-iesalc** [eLearning-BS23/moodle-quizaccess_proctoring#77]
I just checked the new versión, and it seems that uses face-api.js for face recognition in the browser.
I think the minConfidence value, which is use to calibrate the sensibility of the recognition is too high and constantly appears the message."Face not found. Try changing your camera to a better lighting. Thanks."

Ideally can be interesting if this value can be configured in the plugin settins. If you wish y can submit a patch with this change.

Tanks.

**Comment by shadman-ahmed-bs23** [comment]
Hi @unesco-iesalc, 

We will release a new version of the plugin soon, where face-api.js library won't be loaded in frontend if the proctoring plugin doesn't have any face matching service(BS/AWS) enabled in the settings.

Thanks for concern. Cheers!
