### ISSUE TITLE
Date format in proctoring logs

### ISSUE THREAD

**Issue by eptest1** [eLearning-BS23/moodle-quizaccess_proctoring#78]
In the proctoring report logs page, the time is not displayed correctly.
The date format in additional_settings.php uses an 'm', but m is for month
 $data[] = date("Y/M/d H:m:s", $info->timemodified);

Regards
Emilio

**Comment by shadman-ahmed-bs23** [comment]
This issue is merged with master branch.

Thanks for finding out the bug. @eptest1 
Closing this issue.
