### ISSUE TITLE
Proctoring Report missing from Quiz

### ISSUE THREAD

**Issue by toyinal1200** [eLearning-BS23/moodle-quizaccess_proctoring#85]
We are on Moodle 4.1, and testing the Proctoring Plugin with Safe Exam Browser, although the webcam is activated during quiz, the Proctoring report is missing. We will like to evaluate the pictures taken by the proctoring module to confirm that test takers environment is right. The upload pictures ui and ux are really inadequate for uploading 1000 students pictures, username search is missing. How do we get the Proctoring Report?

Thanks

**Comment by shadman-ahmed-bs23** [comment]
Hi @toyinal1200, thanks for using moodle proctoring plugin. 

Can you please provide more details regarding proctoring missing report issue? Like any screenshots of the error message or missing proctoring report. We have released a new version of proctoring plugin for Moodle 4.1. You can download the latest version from plugin directory. 

Regarding the upload picture section, we are working on UI/UX of that feature. We will give the updates in next release.

**Comment by shadman-ahmed-bs23** [comment]
Hi @toyinal1200 , 

Closing this issue for now. If you are still facing any issue, please feel free to reopen this issue.
