### ISSUE TITLE
Error reading from database

### ISSUE THREAD

**Issue by fmido88** [eLearning-BS23/moodle-quizaccess_proctoring#86]
I activated the plugin and works fine till I try to access attempts report of the quiz, it drops an error
Error reading from database
With no debugging information
After uninstall the plugin it worked again

**Comment by shadman-ahmed-bs23** [comment]
Hi @fmido88, Sorry for late response.
Can you please provide more details regarding this issue(Screenshots of error)? We have released a new version. You can also check that out from Moodle Plugins Directory. Please let us know if you are still facing any issue.

Closing this issue. Feel free to reopen it or you can contact us at elearning@brainstation-23.com. Thanks.

**Comment by fmido88** [comment]
Thanks for response
as I mentioned before there is no stack trace for the error
Just when trying to open the quiz grades report or attempts, the page load too long then throw an error
Error reading from the database
That is it
But the proctoring report itself worked fine
When I disabled the plugin the error disappeared

I'll try ti re-install the new version and check if the error still there and inform you.
