### ISSUE TITLE
SQL Error on Install

### ISSUE THREAD

**Issue by cDMB41** [eLearning-BS23/moodle-quizaccess_proctoring#91]
I am having an issue and I think it's because the plugin was installed previously. I can send the entire error, but the initial error thrown is a DDL sql execution error.
Debug info: Table 'mdl_quizaccess_proctoring' already exists

How do I get around this? Do I need to just delete the table in the database or is there something else I need to do to reinstall the plugin?

[Error.sql.zip](https://github.com/eLearning-BS23/moodle-quizaccess_proctoring/files/11358000/Error.sql.zip)

**Comment by shadman-ahmed-bs23** [comment]
Hi @cDMB41 , 

Thanks for your interest in moodle proctoring plugin. Sorry for late response. 

We have released a new version of the plugin. You can find the download link from here: https://moodle.org/plugins/quizaccess_proctoring/versions. 

If the issue still persists, please feel free to reopen this issue with more detailed info of the error. Thanks.
