### ISSUE TITLE
JavaScript:  Identifier 'isCameraAllowed' has already been declared

### ISSUE THREAD

**Issue by amalkowskiint** [eLearning-BS23/moodle-quizaccess_proctoring#92]
`Uncaught SyntaxError: Identifier 'isCameraAllowed' has already been declared (at events.js:1:1)`

this notification is displayed in the browser console.

1.2.45 (2023040600) / Moodle 4.1.3.

**Comment by nehajain2811** [comment]
facing same issues...any update pls

**Comment by nehajain2811** [comment]
Also, please share url for BS website where we can create account and get the key

**Comment by shadman-ahmed-bs23** [comment]
Hi @amalkowskiint and @nehajain2811,

Thanks for using proctoring plugin. We have released a new version of the plugin. You can download the appropriate version for your moodle from this link: https://moodle.org/plugins/quizaccess_proctoring/versions. 

If you are still facing any issue, please let us know with more details (e.g. screenshots).

**Comment by shadman-ahmed-bs23** [comment]
Closing this issue. Please feel free to reopen this issue if you are still facing problem. Thanks.
