### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by paulvivian** [eLearning-BS23/moodle-quizaccess_proctoring#95]
My system dia a plug in update and now I have had to remove the entire plug in as this error appears. Even if the question never had proctoring, its occuring straight away..  It was workg perfectly until the upgrade occured. PLEASE HELP. Happy to give access if it helps to diagnose it. 
![Screen Shot 2023-09-05 at 21 14 10](https://github.com/eLearning-BS23/moodle-quizaccess_proctoring/assets/85493870/7ea799e6-d821-422f-a33e-1da4f0443ee9)

**Comment by shadman-ahmed-bs23** [comment]
Hi @paulvivian, 

Thanks for using proctoring plugin. Please let us know your moodle version and proctoring plugin version. We can then let you know about a solution to fix this issue.

**Comment by paulvivian** [comment]
I am using Moodle Version 4.1.5+ (Build: 20230902) - I believe is the latest version

I was using Proctoring 1.2.45 and everything was great.. 

I then updated to 1.3.0 and the message that I posted previously appears.. 

ALL the quizzes regardless if they had proctoring enabled or not then were blocked by the message so I had to delete the plug in and obvious the database then went as well. 

I just tried to reinstall again whilst the system was quiet with debugging on and no error messages appear in the debug but the same message appears again.. 

Really would like to install the Pro version, as the government agencies we work with what this installed, so we need it fixed please

**Comment by shadman-ahmed-bs23** [comment]
Hi @paulvivian, 

If you are using proctoring free version. We will release a different version for moodle 4.1 and another version for moodle 4.2 in moodle plugin directory tomorrow. 

Are you facing issue with proctoring pro version? If you are facing issue with proctoring pro version, you can give us an email at elearning@brainstation-23.com. Thanks.

**Comment by shadman-ahmed-bs23** [comment]
HI @paulvivian,

We have released two separate versions v1.3.1 for moodle 4.1 and v1.3.2 for moodle 4.2. You can checkout these version from plugin directory. 

Closing this issue. If you still face any issue, please feel free to reopen it.
