### ISSUE TITLE
Exception - Class "mod_quiz\local\access_rule_base" not found

### ISSUE THREAD

**Issue by scloudsa** [eLearning-BS23/moodle-quizaccess_proctoring#96]
Upgraded to Moodle 4.1.5+ and the latest update of Proctoring 1.3.0. The following error appears and breaks the Moodle Dashboard.

See trace below:

Error
Exception - Class "mod_quiz\local\access_rule_base" not found
Debug info:
Error code: generalexceptionmessage
Stack trace:
•	line 28 of /mod/quiz/accessrule/proctoring/rule.php: Error thrown
•	line 834 of /lib/classes/component.php: call to include_once()
•	line 93 of /mod/quiz/accessmanager.php: call to core_component::get_plugin_list_with_class()
•	line 256 of /mod/quiz/accessmanager.php: call to quiz_access_manager::get_rule_classes()
•	line 126 of /mod/quiz/attemptlib.php: call to quiz_access_manager::load_quiz_and_settings()
•	line 2011 of /mod/quiz/lib.php: call to quiz::create()
•	line 8064 of /lib/moodlelib.php: call to mod_quiz_core_calendar_provide_event_action()
•	line 304 of /calendar/classes/local/event/container.php: call to component_callback()
•	line 42 of /calendar/classes/local/event/factories/event_factory.php: call to core_calendar\local\event\container::apply_component_provide_event_action()
•	line 205 of /calendar/classes/local/event/factories/event_abstract_factory.php: call to core_calendar\local\event\factories\event_factory->apply_component_action()
•	line 369 of /calendar/classes/local/event/data_access/event_vault.php: call to core_calendar\local\event\factories\event_abstract_factory->create_instance()
•	line 177 of /calendar/classes/local/event/data_access/event_vault.php: call to core_calendar\local\event\data_access\event_vault->transform_from_database_record()
•	line 95 of /calendar/classes/local/api.php: call to core_calendar\local\event\data_access\event_vault->get_events()
•	line 3521 of /calendar/lib.php: call to core_calendar\local\api::get_events()
•	line 57 of /blocks/calendar_month/block_calendar_month.php: call to calendar_get_view()
•	line 337 of /blocks/moodleblock.class.php: call to block_calendar_month->get_content()
•	line 231 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
•	line 1222 of /lib/blocklib.php: call to block_base->get_content_for_output()
•	line 1280 of /lib/blocklib.php: call to block_manager->create_block_contents()
•	line 377 of /lib/blocklib.php: call to block_manager->ensure_content_created()
•	line 4097 of /lib/outputrenderers.php: call to block_manager->region_has_content()
•	line 66 of /theme/remui/layout/common.php: call to core_renderer->blocks()
•	line 29 of /theme/remui/layout/drawers.php: call to require_once()
•	line 1477 of /lib/outputrenderers.php: call to include()
•	line 1403 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
•	line 179 of /my/index.php: call to core_renderer->header()

Please advise how to resolve the issue?

**Comment by shadman-ahmed-bs23** [comment]
Hi @scloudsa, 

Thanks for using Proctoring Plugin. We will check this issue and get back to you as soon as possible.

**Comment by scloudsa** [comment]
PS. Also, note that the plugin gives the same error when attempting a quiz.

**Comment by oscarvape** [comment]
I have the same error; I shared more information about the version where the plugin is installed.
Moodle 3.11.8+ (Build: 20220812)

The plugin version that was attempted to be updated is 1.3.0.

**Comment by scloudsa** [comment]
> Hi @scloudsa,
> 
> Thanks for using Proctoring Plugin. We will check this issue and get back to you as soon as possible.

Hi, Any progress on resolving this issue?

**Comment by shadman-ahmed-bs23** [comment]
> > Hi @scloudsa,
> > Thanks for using Proctoring Plugin. We will check this issue and get back to you as soon as possible.
> 
> Hi, Any progress on resolving this issue?

Hi, 
Yes, we have solved the issue for Moodle 4.1 and Moodle 4.2. You can find the plugin version 1.3.1(Compatible with Moodle 4.1 and less) in the following branch: 
[MOODLE_401_v1.3.1](https://github.com/eLearning-BS23/moodle-quizaccess_proctoring/tree/MOODLE_401_v1.3.1) in GitHub. We will release the updated plugin in moodle plugin directory shortly. Please note that you have to download the plugin from the mentioned branch and install again in your moodle.

Please let us know if it solves your issue. Thanks.

**Comment by shadman-ahmed-bs23** [comment]
> I have the same error; I shared more information about the version where the plugin is installed. Moodle 3.11.8+ (Build: 20220812)
> 
> The plugin version that was attempted to be updated is 1.3.0.

Hi @oscarvape, 

Thanks for using Proctoring Plugin. You can find the plugin version 1.3.1(Compatible with Moodle 4.1 and less) in the following branch:
[MOODLE_401_v1.3.1](https://github.com/eLearning-BS23/moodle-quizaccess_proctoring/tree/MOODLE_401_v1.3.1) in GitHub. We will release the updated plugin in moodle plugin directory shortly. Please note that you have to download the plugin from the mentioned branch and install again in your moodle.

Please let us know if it solves your issue. Thanks.

**Comment by shadman-ahmed-bs23** [comment]
Hi  @oscarvape and @scloudsa. 

We have release the version v1.3.1 for moodle 4.1 and previous version. You can download the plugin from here: [Moodle Proctoring v1.3.1](https://moodle.org/plugins/quizaccess_proctoring/1.3.1/29922). 

Closing this issue. Please feel free to reopen this issue if you are still facing the problem. Thanks.
