### ISSUE TITLE
Proctoring Plugin slows down Quiz Response

### ISSUE THREAD

**Issue by toyinal1200** [eLearning-BS23/moodle-quizaccess_proctoring#98]
Im impressed with your Proctoring Plugin, but we noticed that with the proctoring enabled on a quiz, Each question freezes for about 30 to 45 seconds before students input are accepted. There is no freezing of quiz when ran without the plugin. This quiz freezing happened on both low end or high end students devices. We are on Moodle 4.1
I think this is related to the browser freezing reported on Issue #76. Is there a way to disable the face detection until this issue is resolved

**Comment by shadman-ahmed-bs23** [comment]
Hi there @toyinal1200,

Thanks for using proctoring plugin and your kind words. Sorry about the issues that you faced. Currently, there is no way to disable the face detection from settings. We will work on releasing a version of proctoring without continuous face detection in the next release.

**Comment by shadman-ahmed-bs23** [comment]
Closing this issue for now. Feel free to reopen it if you have any other questions. Thanks.
